name: sumry_app
description: An app for the text summarizer api.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  hovering: ^1.0.4
  flutter_riverpod: ^1.0.4
  http: ^0.13.5
  file_picker: ^5.0.1

  # Firebase Database

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/

