name: sumry_man
description: An app for the text summarizer api.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  path_provider: ^2.0.11
  date_format: ^2.0.6
  hovering: ^1.0.4
  flutter_riverpod: ^1.0.4
  http: ^0.13.5
  file_picker: ^5.0.1
  http_parser: ^4.0.1
  dio: ^4.0.6
  pdf: ^3.8.3
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  firebase_database: ^7.2.1
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1+1

  # Firebase Database

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/

