// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYm4jLZ63qTjEsoLvFGujucoPD0tqTZ7U',
    appId: '1:585684131203:web:4081f9c28038ea07d26ab6',
    messagingSenderId: '585684131203',
    projectId: 'sumry-man-app',
    authDomain: 'sumry-man-app.firebaseapp.com',
    storageBucket: 'sumry-man-app.appspot.com',
    measurementId: 'G-4ERM4NW71Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeNPxXONIMAeMaxM9P97pvznzixZMJxH4',
    appId: '1:585684131203:android:510e7781feec3782d26ab6',
    messagingSenderId: '585684131203',
    projectId: 'sumry-man-app',
    storageBucket: 'sumry-man-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Dd18gc9Et71wc8k9AvpswBKg_5gu6BM',
    appId: '1:585684131203:ios:4fddb55c96c4be64d26ab6',
    messagingSenderId: '585684131203',
    projectId: 'sumry-man-app',
    storageBucket: 'sumry-man-app.appspot.com',
    iosClientId: '585684131203-gm47cm4i29a8vt9raib70nk4ud0nf63j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sumryApp',
  );
}
